### ISSUE TITLE
npm install jsreport-phantom-pdf . - errors

### ISSUE THREAD

**Issue by wibobm** [jsreport/jsreport-phantom-pdf#35]
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/bob/Developer/summaft/jsreport/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/bob/Developer/summaft/jsreport/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/bob/Developer/summaft/jsreport/node_modules/phantom-workers/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by bjrmatos** [comment]
hi! i can't reproduce this error. i use OSX with node `8.13.0`, after installing `jsreport-phantom-pdf@2.2.0` i don't see that error during installation or at runtime. do you have more details that can help to replicate your issue?

**Comment by wibobm** [comment]
Ah.. it seems easily reproduced with node 12.4.0.  I'll try 8.13.0 -- I'm sure that will work if it does for you.

**Comment by bjrmatos** [comment]
sure, i think none of us has installed node 12 yet, so we aren't aware of possible problems there. newer versions of node should definitely be supported, we just need to find the time to test. thanks for reporting.
