### ISSUE TITLE
error with node16 and phantom-server strategy

### ISSUE THREAD

**Issue by abenhamdine** [jsreport/jsreport-phantom-pdf#39]
after upgrading to nodejs 16 we have an error 'phantomjs not found'

```
2021-07-03T18:32:46+02:00 Error: Cannot find module 'phantomjs'
2021-07-03T18:32:46+02:00 Require stack:
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-workers/lib/phantomWorker.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-workers/lib/phantomManager.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-workers/index.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/serverStrategy.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/index.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/jsreport-phantom-pdf/lib/phantom.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/jsreport-phantom-pdf/index.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/reports/jsreportConfigured.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/reports/generateReportFile.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/reports/reportsMgr.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/reports/routerReports.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/app/app.js
2021-07-03T18:32:46+02:00 - /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/server/server.js
2021-07-03T18:32:46+02:00 at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
2021-07-03T18:32:46+02:00 at Function.Module._load (node:internal/modules/cjs/loader:772:27)
2021-07-03T18:32:46+02:00 at Module.require (node:internal/modules/cjs/loader:999:19)
2021-07-03T18:32:46+02:00 at require (node:internal/modules/cjs/helpers:93:18)
2021-07-03T18:32:46+02:00 at new module.exports (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-workers/lib/phantomWorker.js:28:36)
2021-07-03T18:32:46+02:00 at module.exports.PhantomManager.start (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-workers/lib/phantomManager.js:42:37)
2021-07-03T18:32:46+02:00 at ensurePhantom (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/serverStrategy.js:19:13)
2021-07-03T18:32:46+02:00 at module.exports (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/serverStrategy.js:40:5)
2021-07-03T18:32:46+02:00 at /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:69:50
2021-07-03T18:32:46+02:00 at /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:30:17
2021-07-03T18:32:46+02:00 at writeHtmlFile (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:10:16)
2021-07-03T18:32:46+02:00 at /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:26:13
2021-07-03T18:32:46+02:00 at writeHtmlFile (/home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:10:16)
2021-07-03T18:32:46+02:00 at /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/phantom-html-to-pdf/lib/conversion.js:22:9
2021-07-03T18:32:46+02:00 at /home/bas/app_a3accf6f-face-4001-9d7e-ba9f1379feb7/node_modules/graceful-fs/graceful-fs.js:61:14
2021-07-03T18:32:46+02:00 at FSReqCallback.oncomplete (node:fs:185:23)
```

**Comment by pofider** [comment]
Hm, this works for me also on node 16.
Maybe try to add `phantomjs` module to your deps in package.json explicitly.

Note phantomjs project is archived. Sooner or later it will stop working with newer versions of nodejs.
You should migrate to the [chrome-pdf](https://jsreport.net/learn/chrome-pdf)

**Comment by abenhamdine** [comment]
> Hm, this works for me also on node 16.
> Maybe try to add `phantomjs` module to your deps in package.json explicitly.
> 

thx for your response, I will try  !

> Note phantomjs project is archived. Sooner or later it will stop working with newer versions of nodejs.
> You should migrate to the [chrome-pdf](https://jsreport.net/learn/chrome-pdf)

Yes definitely, you're right. We have just started the migration, but chrome-pdf renders templates a bit differently, and we have to track all the visual changes.
